name: Test
on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Test
        run: dotnet test --logger "trx;LogFileName=TestResults-Vignette.Core.Tests.trx"

      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: TestResults-Vignette.Core.Tests
          path: ${{ github.workspace }}/Vignette.Core.Tests/TestResults/TestResults-Vignette.Core.Tests.trx

